require 'json'
require 'fileutils'
require_relative 'chromebrew/lib/color'

LATEST_PACKAGE_LIST = JSON.load_file('output/latest.json')

Dir.glob('output/*.rb') do |package|
  pkg_name = File.basename(package, '.rb')
  crew_ver = File.read("chromebrew/packages/#{pkg_name}.rb")[/version ['"](.+?)['"]/, 1]
  latest_ver = LATEST_PACKAGE_LIST[pkg_name]

  if crew_ver != LATEST_PACKAGE_LIST[pkg_name]
    puts "Update found for #{pkg_name}: #{crew_ver} => #{latest_ver}".lightcyan

    File.write '/tmp/pr.txt', <<~EOF
      ### Package information
      - Package name: #{pkg_name}
      - Old version: #{crew_ver}
      - New version: #{latest_ver}

      This PR is generated by [crew-update-checker](https://github.com/supechicken/crew-update-checker)
    EOF

    Dir.chdir 'chromebrew' do
      system 'git', 'checkout', '-b', "update_#{pkg_name}_#{Time.now.strftime("%Y%m%d")}"
      system 'git', 'push', '--set-upstream', 'origin', "update_#{pkg_name}_#{Time.now.strftime("%Y%m%d")}"

      FileUtils.cp File.join('..', package), "packages/#{pkg_name}.rb"

      system 'git', 'add', "packages/#{pkg_name}.rb"
      system 'git', 'commit', '-m', "Auto-generated update for #{pkg_name} (#{latest_ver})"
      system 'git', 'push'

      # create PR in chromebrew repo
      system "gh pr create -R chromebrew/chromebrew -B master --reviewer chromebrew/active --title 'Auto-generated update for #{pkg_name} (#{latest_ver})' -F /tmp/pr.txt"

      system 'git', 'checkout', 'master'
    end
  end
end
